### ISSUE TITLE
is there any instructions?

### ISSUE THREAD

**Issue by albertyou2** [simozmp/pedestrian#1]
hey @simozmp 
iis there any instructions? or how to make it?any makefile?
thank you !

**Comment by glunetto** [comment]
Hi, there are two things to say, the first one is that this app is a prototype and is also incomplete, the second thing is that we uploaded the entire Android studio project so if you wanna try the app you have to compile it with Android studio (I suppose).

One last "problem" is that we disabled by code the main functionalities of the app because the day we stopped the work on the app our goal was to improve the performance  and so if you want to try it you have to understand how to enable the various functionalities by code first.

I apologise that I can't help you more.

Greetings

Gaspare Emmanuel Lunetto


________________________________

**Comment by albertyou2** [comment]
thank you for relpy! i got it
have nice day!
